
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Docker Quickstart Terminal for OSX puts the docker binary into
# /usr/local/bin/ and not /usr/bin/ (as per Ubuntu/Debian)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker

