
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Docker Quickstart Terminal for OSX uses docker-machine to forward
# docker commands to a default boot2docker VM. On this VM
# the docker binary lives at /usr/local/bin/ and not /usr/bin/
# (as per Ubuntu/Debian)
#
# The cyber-dojo web container is a docker-in-docker container,
# it calls docker commands (eg to see what language-images are pulled).
# There are 3 ways I can think of to allow these docker commands
# to work *inside* the web container.
#
#    1. volume-mount the docker-binary and docker-socket
#       from the boot2docker VM on the server.
#
#    2. install the docker-client *inside* the image
#       as part of its Dockerfile.
#
#    3. volume-mount the docker-binary, but not the docker-socket
#       and *inside* the container, set the DOCKER_CERT_PATH to point
#       to pem files (inside the image), set DOCKER_HOST to the server's
#       IP/port, set DOCKER_MACHINE_NAME to the server's name,
#       set DOCKER_TLS_VERIFY to 1. Then the docker binary, when
#       called from inside the container, will not attempt to access
#       the docker-socket but will instead ssh tunnel out to the
#       server itself, and the server will run the command, and the
#       server will have access to the docker-socket.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  volumes:
    - /usr/local/bin/docker:/usr/local/bin/docker
