
# volumes_from entries *replace* values from the original service
# See https://docs.docker.com/compose/extends/

web:
  volumes_from:
    - exercises:ro
    - languages:ro
    - katas:rw
    - tmp:rw
    - test:rw

test:
  image: cyberdojofoundation/test
  entrypoint: /bin/sh

