# docker-compose build --no-cache
# docker-compose up
# Don't forget to ensure port 80 is open


nginx:
  build: .
  dockerfile: ./docker/nginx_image/Dockerfile
  ports:
      - "80:80"
  links:
      - "web:cyberdojo_web"


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# For running on a debian-jessie server after installing docker
# and docker-compose as per instructions on Docker web pages.
# For info on the apparmour volume mount fix see
# https://github.com/SvenDowideit/dockerfiles/issues/17
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  build: .
  dockerfile: ./docker/server_image_rails/Dockerfile
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /usr/lib/x86_64-linux-gnu/libapparmor.so.1.2.0:/usr/lib/x86_64-linux-gnu/libapparmor.so.1
  volumes_from:
    - exercises:ro
    - languages:ro
    - tmp:rw
    - katas:rw
  ports:
    - "3000:3000"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# data-containers
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

exercises:
  build: ./exercises
  entrypoint: /bin/sh
  container_name: cyber-dojo-exercises-data-container


languages:
  build: ./languages
  entrypoint: /bin/sh
  container_name: cyber-dojo-languages-data-container


tmp:
  build: ./docker/tmp_image
  entrypoint: /bin/sh
  container_name: cyber-dojo-tmp-data-container


katas:
  build: ./docker/katas_image
  entrypoint: /bin/sh
  container_name: cyber-dojo-katas-data-container
