
# Partial docker-compose.yml file for bringing up cyber-dojo.
# Must be combined with a docker-compose extension file which
# adds web volume mounts for docker itself (docker in docker).

nginx:
  image: cyberdojofoundation/nginx
  links:
    - "web:cyberdojo_web"
  ports:
    - "80:80"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  environment:
    - CYBER_DOJO_LANGUAGES_ROOT=${CYBER_DOJO_ROOT}/languages
    - CYBER_DOJO_EXERCISES_ROOT=${CYBER_DOJO_ROOT}/exercises
    - CYBER_DOJO_CACHES_ROOT=${CYBER_DOJO_ROOT}/caches
    - CYBER_DOJO_KATAS_ROOT=${CYBER_DOJO_ROOT}/katas
    - CYBER_DOJO_RUNNER_CLASS=DockerTmpRunner
    - CYBER_DOJO_KATAS_CLASS=HostDiskKatas
    - CYBER_DOJO_SHELL_CLASS=HostShell
    - CYBER_DOJO_DISK_CLASS=HostDisk
    - CYBER_DOJO_LOG_CLASS=HostLog
    - CYBER_DOJO_GIT_CLASS=HostGit
  image: cyberdojofoundation/web
  volumes_from:
    - exercises:ro
    - languages:ro
    - katas:rw
    - tmp:rw
    - test:rw
  ports:
    - "3000:3000"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

languages:
  image: cyberdojofoundation/languages
  entrypoint: /bin/sh

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

exercises:
  image: cyberdojofoundation/exercises
  entrypoint: /bin/sh

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

katas:
  image: cyberdojofoundation/katas
  entrypoint: /bin/sh

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

tmp:
  image: cyberdojofoundation/tmp
  entrypoint: /bin/sh
  container_name: cyberdojo_tmp_data_container

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

test:
  image: cyberdojofoundation/test
  entrypoint: /bin/sh
