
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# For info on the apparmour volume mount see
# https://github.com/SvenDowideit/dockerfiles/issues/17
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /usr/lib/x86_64-linux-gnu/libapparmor.so.1.1.0:/usr/lib/x86_64-linux-gnu/libapparmor.so.1
