
nginx:
  extends:
    file: docker-compose-base.yml
    service: nginx
  links:
    - "web:cyberdojo_web"

web:
  extends:
    file: docker-compose-base.yml
    service: web
  environment:
    - CYBER_DOJO_RUNNER_CLASS=DockerKatasVolumeRunner
  volumes:
    - ${CYBER_DOJO_KATAS_ROOT}:${KATAS_DIR}:rw

