
nginx:
  extends:
    file: docker-compose-base.yml
    service: nginx
  links:
    - "web:cyberdojo_web"

web:
  extends:
    file: docker-compose-base.yml
    service: web
  environment:
    - CYBER_DOJO_RUNNER_CLASS=DockerKatasDataContainerRunner
  volumes_from:
    - cyber-dojo-katas

