

nginx:
  image: cyberdojofoundation/nginx
  container_name: cdf-nginx
  links:
    - "web:cyberdojo_web"
  ports:
    - "80:80"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  user: cyber-dojo
  image: cyberdojofoundation/web
  container_name: cdf-web
  command: rails server --environment=development
  environment:
    - CYBER_DOJO_SHELL_CLASS=HostShell
    - CYBER_DOJO_DISK_CLASS=HostDisk
    - CYBER_DOJO_LOG_CLASS=StdoutLog
    - CYBER_DOJO_GIT_CLASS=HostGit
    - CYBER_DOJO_LANGUAGES_ROOT=${CYBER_DOJO_HOME}/app/languages
    - CYBER_DOJO_EXERCISES_ROOT=${CYBER_DOJO_HOME}/app/exercises
    - CYBER_DOJO_KATAS_CLASS
    - CYBER_DOJO_KATAS_ROOT
    - CYBER_DOJO_RUNNER_CLASS
    - CYBER_DOJO_RUNNER_SUDO
    - CYBER_DOJO_RUNNER_TIMEOUT
  ports:
    - "3000:3000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - cdf-katas-DATA-CONTAINER:rw
    - languages:ro
    - exercises:ro
    - rails-app:ro
    - rails-log:rw
    - rails-tmp:rw
    - test:ro

languages:
  image: cyberdojofoundation/languages
  command: echo "cdfLanguagesDC"
  container_name: cdf-languages-DATA-CONTAINER

exercises:
  image: cyberdojofoundation/exercises
  command: echo "cdfExercisesDC"
  container_name: cdf-exercises-DATA-CONTAINER

rails-app:
  image: cyberdojofoundation/rails-app
  command: echo "cdfRailsAppDC"
  container_name: cdf-rails-app-DATA-CONTAINER

rails-log:
  image: cyberdojofoundation/rails-log
  command: echo "cdfRailsLogDC"
  container_name: cdf-rails-log-DATA-CONTAINER

rails-tmp:
  image: cyberdojofoundation/rails-tmp
  command: echo "cdfRailsTmpDC"
  container_name: cdf-rails-tmp-DATA-CONTAINER

test:
  image: cyberdojofoundation/test
  command: echo "cdfTestDC"
  container_name: cdf-test-DATA-CONTAINER


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# The cyber-dojo script uses this file to find out the
# service names. It assumes the service name (eg web) is the
# tag name for the associated docker image (eg cyberdojofoundation/web)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Variable-substition happens in docker-compose yml files
# such as this one, but *not* in env_file:'s
# Since I use variable-substitution in my environment
# I don't use an env_file:
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
