
# Partial docker-compose.yml file for bringing up cyber-dojo.
# Must be combined with a docker-compose extension file which
# adds web volume mounts for docker itself (docker from docker).
#
# Note that variable-substition happens in docker-compose yml files
# such as this one, but *not* in env_file:'s
# Since I use variable-substitution in many of my environment
# variables I don't use an env_file:

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

nginx:
  image: cyberdojofoundation/nginx
  links:
    - "web:cyberdojo_web"
  ports:
    - "80:80"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  command: rails server --environment=${CYBER_DOJO_UP}
  environment:
    - CYBER_DOJO_LANGUAGES_ROOT=${CYBER_DOJO_ROOT}/languages
    - CYBER_DOJO_EXERCISES_ROOT=${CYBER_DOJO_ROOT}/exercises
    - CYBER_DOJO_CACHES_ROOT=${CYBER_DOJO_ROOT}/caches
    - CYBER_DOJO_KATAS_ROOT=${CYBER_DOJO_ROOT}/katas
    - CYBER_DOJO_RUNNER_CLASS=DockerFromDockerRunner
    - CYBER_DOJO_KATAS_CLASS=HostDiskKatas
    - CYBER_DOJO_SHELL_CLASS=HostShell
    - CYBER_DOJO_DISK_CLASS=HostDisk
    - CYBER_DOJO_LOG_CLASS=HostLog
    - CYBER_DOJO_GIT_CLASS=HostGit
  image: cyberdojofoundation/web
  ports:
    - "3000:3000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - languages:ro
    - exercises:ro
    - katas:rw
    - test:rw
    - tmp:rw

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

languages:
  entrypoint: /bin/sh
  image: cyberdojofoundation/languages

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

exercises:
  entrypoint: /bin/sh
  image: cyberdojofoundation/exercises

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

katas:
  entrypoint: /bin/sh
  image: cyberdojofoundation/katas

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

test:
  entrypoint: /bin/sh
  image: cyberdojofoundation/test

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

tmp:
  container_name: cyberdojo_tmp_data_container
  entrypoint: /bin/sh
  image: cyberdojofoundation/tmp
