

nginx:
  image: cyberdojofoundation/nginx
  container_name: cyber-dojo-nginx
  links:
    - "web:cyberdojo_web"
  ports:
    - "80:80"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  user: cyber-dojo
  image: cyberdojofoundation/web
  container_name: cyber-dojo-server
  command: rails server --environment=${CYBER_DOJO_ENV}
  environment:
    - CYBER_DOJO_LANGUAGES_ROOT
    - CYBER_DOJO_EXERCISES_ROOT
    - CYBER_DOJO_SHELL_CLASS
    - CYBER_DOJO_DISK_CLASS
    - CYBER_DOJO_LOG_CLASS
    - CYBER_DOJO_GIT_CLASS
    - CYBER_DOJO_KATAS_ROOT
    - CYBER_DOJO_KATAS_CLASS
    - CYBER_DOJO_RUNNER_CLASS
    - CYBER_DOJO_RUNNER_SUDO
    - CYBER_DOJO_RUNNER_TIMEOUT
  ports:
    - "3000:3000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - cyber-dojo-katas:rw
    - languages:ro
    - exercises:ro
    - rails-app:rw
    - rails-log:rw
    - rails-tmp:rw
    - test:ro


# Cannot specify
#    - rails-app:ro
# Get error
# ERROR: Cannot start container 84297ba318348d68108d5bd45aa13c2f96111603eb0db930a34779756a887c73:
# [9] System error: mkdir
#    /mnt/sda1/var/lib/docker/aufs/mnt/
#    4d28577fb5acdb3c80ce1868e3baeb84571445cd892c46db2f78781dc640a2a4/usr/src/cyber-dojo/katas:
#    read-only file system
# I'm guessing this is because rails-app includes files at the /usr/src/cyber-dojo/ level
# namely config.ru

languages:
  image: cyberdojofoundation/languages
  command: echo "DC:cdf/languages"

exercises:
  image: cyberdojofoundation/exercises
  command: echo "DC:cdf/exercises"

rails-app:
  image: cyberdojofoundation/rails-app
  command: echo "DC:cdf/rails-app"

rails-log:
  image: cyberdojofoundation/rails-log
  command: echo "DC:cdf/rails-log"

rails-tmp:
  image: cyberdojofoundation/rails-tmp
  command: echo "DC:cdf/rails-tmp"

test:
  image: cyberdojofoundation/test
  command: echo "DC:cdf/test"


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# The cyber-dojo script uses this file to find out the
# service names. It assumes the service name (eg web) is the
# tag name for the associated docker image (eg cyberdojofoundation/web)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Variable-substition happens in docker-compose yml files
# such as this one, but *not* in env_file:'s
# Since I use variable-substitution in my environment
# I don't use an env_file:
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
