
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Docker QuickStart Terminal for OSX does not put the docker
# binary into /usr/bin/docker (as per Ubuntu/Debian)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker
